apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinity
  template:
    metadata:
      labels:
        app: infinity
    spec:
      containers:
      - name: infinity
        image: turok/infinity
        ports:
        - containerPort: 80
        env:
        - name: GO_ENV
          value: "http://foo-service"
